[package]
name = "mdbook-i18n-helpers"
version = "0.3.0"
authors = ["Martin Geisler <mgeisler@google.com>"]
categories = ["command-line-utilities", "localization"]
edition = "2021"
keywords = ["mdbook", "i18n", "translation", "gettext"]
license = "Apache-2.0"
repository = "https://github.com/google/mdbook-i18n-helpers"
description = "Plugins for a mdbook translation workflow based on Gettext."

[dependencies]
anyhow = "1.0.68"
chrono = { version = "0.4.31", default-features = false, features = ["alloc"] }
mdbook = { version = "0.4.36", default-features = false }
polib = "0.2.0"
pulldown-cmark = { version = "0.9.2", default-features = false }
pulldown-cmark-to-cmark = "11.0.2"
regex = "1.9.4"
semver = "1.0.21"
serde_json = "1.0.91"
syntect = "5.1.0"
textwrap = { version = "0.16.0", default-features = false }

[dev-dependencies]
pretty_assertions = "1.3.0"
tempfile = "3.9.0"
